//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectNewsComment
    {
        public int ProjectNewsCommentID { get; set; }
        public int FromUserID { get; set; }
        public int ProjectNewsID { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual ProjectNew ProjectNew { get; set; }
    }
}
