//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scope
    {
        public Scope()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ScopeID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
