//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UsersInfoID { get; set; }
        public int UserID { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Middle { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Citizenship { get; set; }
        public string PasportSerie { get; set; }
        public string PasportNumber { get; set; }
        public System.DateTime PasportIssueDate { get; set; }
        public string PasportIssuedBy { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string AboutMyself { get; set; }
    }
}
